/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4 tab-width: 4 -*- */
/*
 * File: i_callbacks.c
 *
 * gEDA - GPL Electronic Design Automation
 * gschem - gEDA Schematic Capture
 * Copyright (C) 1998-2015 Ales Hvezda
 * Copyright (C) 1998-2015 gEDA Contributors (see ChangeLog for details)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA
 */

#include <gschem.h>
#include <geda_debug.h>

#define I_DO_DECLARE
#include "i_command.h"

#include <geda_debug.h>

/*! \brief */
#define DELIMITERS ", "

/*! \def DEFINE_I_CALLBACK
 * Every i_callback functions have the same footprint
 */
#define DEFINE_I_CALLBACK(name) void i_callback_ ## name I_CALLBACK_ARGUMENTS

/*! \section callback-intro Callback Functions
 *
 * Don't use the widget parameter in these callback function, or do some
 * checking since these routines are usually called with widget = NULL,
 * data = 0 (will be w_current hack)
 *
 * \note WEH: The 4th parameter to the i_command_process function called
 *       by most of the actions is an optional string pointer, typical
 *       generated by keyboard, we don't utilize this here (yet) ;
 */

/*! \brief Zoom Pan initiated by Keyboard Hotkey
 *  \par Function Description
 *  This is a callback function for the Zoom Pan Hotkey action.
 */
DEFINE_I_CALLBACK(view_pan_hotkey)
{
  if(w_current != NULL) {

    int wx, wy;

    if (!i_window_get_pointer_position(w_current, FALSE, &wx, &wy))
      return;

    i_pan_world(w_current, wx, wy);

    if (w_current->undo_panzoom) {
      o_undo_savestate(w_current, UNDO_VIEWPORT_ONLY);
    }
  }
}

/*! \brief Callback function that moves the viewport to the left.
 *  \par Function Description
 * The distance can be set with "keyboardpan-gain" scheme callback.
 */
DEFINE_I_CALLBACK(view_pan_left)
{
  if(w_current != NULL)
    i_pan_world_mouse(w_current, w_current->keyboardpan_gain, 0);
}

/*! \brief Callback function that moves the viewport to the right.
 *  \par Function Description
 * The distance can be set with "keyboardpan-gain" scheme callback.
 */
DEFINE_I_CALLBACK(view_pan_right)
{
  if(w_current != NULL)
    i_pan_world_mouse(w_current, -w_current->keyboardpan_gain, 0);
    /* yes, that's a negative sign there */
}

/*! \brief Callback function that moves the viewport up.
 *  \par Function Description
 * The distance can be set with "keyboardpan-gain" scheme callback.
 */
DEFINE_I_CALLBACK(view_pan_up)
{
  if(w_current != NULL)
    i_pan_world_mouse(w_current, 0, w_current->keyboardpan_gain);
}

/*! \brief Callback function that moves the viewport down.
 *  \par Function Description
 * The distance can be set with "keyboardpan-gain" scheme callback.
 */
DEFINE_I_CALLBACK(view_pan_down)
{
  if(w_current != NULL)
    i_pan_world_mouse(w_current, 0, -w_current->keyboardpan_gain);
    /* yes, that's a negative sign there */
}

/** \defgroup file-menu File Menu Callback Functions
 * @{
 */

/*! \brief Create New Blank Page
 *  \par Function Description
 *  This is a callback function for the File New API.
 *  The function calls i_command to process the action.
 *  \note the file-new action is similar to page new but does
 *  not automatically add a title-block
 */
DEFINE_I_CALLBACK(file_new)
{
  i_command_process(w_current, "file-new", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief File Open action
 *  \par Function Description
 *  This is a callback function for the File Open API.
 *  The function calls i_command to process the action.
 */
DEFINE_I_CALLBACK(file_open)
{
  i_command_process(w_current, "file-open", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Save File command action
 *  \par Function Description
 *  This is a callback function for the File Save API
 *  The function calls i_command to process the action.
 */
DEFINE_I_CALLBACK(file_save)
{
  i_command_process(w_current, "file-save", 0, NULL, ID_ORIGIN_SCM);
}

/** @} end group file-menu */

/*! \brief Page Close
 *  \par Function Description
 *  This is a callback function for the New Page API.
 *  The function calls i_command to process the action.
 */
DEFINE_I_CALLBACK(page_close)
{
  i_command_process(w_current, "page-close", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Page Discard
 *  \par Function Description
 *  This is a callback function for the Discard Page API.
 *  The function calls i_command to process the action.
 */
DEFINE_I_CALLBACK(page_discard)
{
  i_command_process(w_current, "page-discard", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Cancel Everthing
 *  \par Function Description
 *
 *  \note Do NOT use the widget parameter in this one since it is being
 *        called with a null.
 */
DEFINE_I_CALLBACK(cancel)
{
  switch (w_current->event_state) {
    case COMPMODE:

      if (w_current->cswindow) {

        /* user hit escape key when placing components */

        /* Undraw any outline of the place list */
        o_place_invalidate_rubber (w_current, FALSE);
        w_current->rubber_visible = FALSE;

        /* De-select the lists in the component selector */
        x_compselect_deselect (w_current);

        /* Present the component selector again */
        g_object_set (G_OBJECT(w_current->cswindow), "hidden", FALSE, NULL);
      }
      break;

    case MOVEMODE:
    case DRAGMOVE:

      if (w_current->inside_action) {

        /* If we're cancelling while inside a move action, free the place
         * list and destroy the stretch_list */
          o_move_cancel (w_current);
      }
      break;

    case GRIPS:
      /* If we're cancelling from a grip action, call the specific cancel
       * routine to reset the visibility of the object being modified */
      o_grips_cancel (w_current);

    case SELECT:
    case STARTSELECT:
      o_select_cancel_events(w_current);
      break;

    default:
      break;

  }

  if (o_select_is_selection (w_current)) {
    o_select_unselect_all(w_current);
  }

  if (Current_Page->place_list) {
    s_object_release_objects(Current_Page->place_list);
    Current_Page->place_list = NULL;
  }

  /* Clear the key guile command-sequence */
  g_keys_reset (w_current);

  o_invalidate_all (w_current);
  i_status_set_state(w_current, SELECT);
  w_current->inside_action = FALSE;
}

/** \defgroup help-menu Help Menu Callback Functions
 * @{
 */

/*! \brief Help About Action Callback Responder API Function
 *  \par Function Description
 *  This is a callback function for the Help About API
 *  The function calls i_command to launch the Help About Dialog.
 */
DEFINE_I_CALLBACK(help_show_manual)
{
  i_command_process(w_current, "help-show-manual", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Help Hotkeys Action Callback Responder API Function
 *  \par Function Description
 *  This is a callback function for the Help Hotkeys API
 *  The function calls i_command to launch the Help Hotkeys Dialog.
 *
 *  \note
 *  WEH: like it!, could have icons too!
 */
DEFINE_I_CALLBACK(help_show_hotkeys)
{
  i_command_process(w_current, "help-show-hotkeys", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Help About Action Callback Responder API Function
 *  \par Function Description
 *  This is a callback function for the Help About API
 *  The function calls i_command to launch the Help About Dialog.
 */
DEFINE_I_CALLBACK(help_show_faq)
{
  i_command_process(w_current, "help-show-faq", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Help About Action Callback Responder API Function
 *  \par Function Description
 *  This is a callback function for the Help About API
 *  The function calls i_command to launch the Help About Dialog.
 */
DEFINE_I_CALLBACK(help_show_wiki)
{
  i_command_process(w_current, "help-show-wiki", 0, NULL, ID_ORIGIN_SCM);
}

/*! \brief Help About Action Callback Responder API Function
 *  \par Function Description
 *  This is a callback function for the Help About API
 *  The function calls i_command to launch the Help About Dialog.
 */
DEFINE_I_CALLBACK(help_show_about)
{
  i_command_process(w_current, "help-show-about", 0, NULL, ID_ORIGIN_SCM);
}

/** @} end group help-menu */

/*! \brief Close main window callback
 *  \par Function Description
 *  When invoked (via signal delete_event), closes the current window
 *  when the user clicks the close button on the window which sends a
 *  DELETE signal to the app
 *
 *  \remarks This is a special callback function which cannot use the
 *           above DEFINE_I_CALLBACK macro
 */
bool i_callback_close_wm ( GtkWidget      *widget, GdkEvent *event,
                           GschemToplevel *w_current )
{
  x_window_close(w_current);

  /* Stop further propagation of the delete_event signal for window:
   * If user has cancelled the close the window should obvioulsy not
   * be destroyed, otherwise window has already been destroyed and
   * there is nothing more to do
   */
  return TRUE;
}
