#!/bin/sh
LOG=test-suite.log

# -- For Colorization ---
RED='\033[0;40;;31m'
GREEN='\033[0;40;;32m'
NORMAL='\033[00m'

rundir=${TESTDIR}

input=$1

. ./TEST_FUNCS

result=0;

if test -f $input ; then

  # get the base name of the test file without the directory
  filename=$(basename $input)

  # get the base name of the test file without the extension
  filebase=$(basename $input .${input##*.})

  cp $input $rundir/

  cd $rundir/

  $TEST_APP -q -pzx "(gschem-log \"Running Log Diff Tests\")(gschem-exit)" $filename > ${LOG} 2>&1
  ret_code=$?

  if test $ret_code -ne 0 ; then
    cat << EOF >> ${LOG}
      $TEST_APP -q -pzx "(gschem-log \"Running Log Diff Tests\")(gschem-exit)" $filename
      exited with code ${ret_code}
EOF
  fi

  if test -d "../logs" ; then

    # Get the latest file in the gschem log directory
    newlog=$(ls -Art ../logs | tail -n 1)

    if test -z "$newlog" ; then
      echo "Error: Was the log file created in the right place?"
      ls -l "../logs/*"
      exit 1;
    fi
    testlog="${filebase}.log"

    # Remove the version line and write to run directory
    grep -v "version" ../logs/$newlog > temp && mv temp ${testlog}
  else
    echo "Error: host directory \"../logs\" is not accessible!"
    exit 0;
  fi

  cd ..

  # Rename the log file in the log subdirectory
  mv logs/$newlog logs/$testlog

  goldenlog=golden/${filebase}.log

  if test $regenerating ; then
    vecho "Regenerating ${goldenlog}"
    cp "run/${testlog}" ${goldenlog}
    result=$?;
  elif test -f $goldenlog ; then
    vecho "Comparing run/${testlog} to ${goldenlog}..."
    diff "run/${testlog}" "${goldenlog}"
    result=$?
    if [ $result -eq 0 ]; then
       echo $GREEN"PASSED:$NORMAL" $filebase; \
    else
       echo $RED"FAILED:$NORMAL" $filebase; \
    fi
  else
    echo "$goldenlog Does not exist, try regenerating the test reference"
    result=1;
  fi

else
  result=1;
fi

exit $result
